import {useCallback,useEffect,useState,useRef} from 'react';
import {App as AntApp,Button,Drawer,Form,Input,InputNumber,Modal,Select,Slider,Spin,Tag,Tooltip} from 'antd';
import {Activity,ArrowDownToLine,ArrowRight,Check,ChevronRight,Clock3,Command,GitBranch,History,LayoutDashboard,MapPin,Pause,Play,Radio,RotateCcw,Settings2,ShieldCheck,TrainFront,TriangleAlert,Waypoints,Zap} from 'lucide-react';
import {MetricSettings,metricLabels} from './MetricSettings';
import {DispatchPolicy} from './DispatchPolicy';
import {FleetEditor} from './FleetEditor';
import {Timeline} from './Timeline';
import {RailMap,TrackDiagram} from './Map';
import {SpeedChart,TrainChart} from './Charts';
import {api,clock,minutes,useDispatch} from './store';
import type {Plan,Profile,Snapshot,Topology} from './types';

const statusName:Record<string,string>={waiting:'На станции',moving:'В движении',completed:'Прибыл',scheduled:'По расписанию',queued:'Ожидает допуска'};
const incidentName:Record<string,string>={delay:'Задержка поезда',closure:'Закрытие перегона',signal:'Неисправность сигнала',speed_restriction:'Ограничение скорости (50%)'};

export default function App(){
 const {message,modal}=AntApp.useApp();
 const paintEvent=useRef<{seq:number;ws:WebSocket;received:number}|null>(null);
 const {snapshot,selected,select,connected,lastUpdate,setSnapshot,setConnected}=useDispatch();
 const [topology,setTopology]=useState<Topology|null>(null),[baseline,setBaseline]=useState<Plan|null>(null),[plans,setPlans]=useState<Plan[]>([]),[preview,setPreview]=useState<Plan|null>(null);
 const [logicCases,setLogicCases]=useState<string[]>([]),[logicCase,setLogicCase]=useState('main_track_closure');
 const [profile,setProfile]=useState<Profile|null>(null),[allCountry,setAllCountry]=useState(false),[mapTab,setMapTab]=useState('map');
 const [incidentOpen,setIncidentOpen]=useState(false),[incidentKind,setIncidentKind]=useState('closure'),[incidentTarget,setIncidentTarget]=useState('section-1'),[duration,setDuration]=useState(10);
 const [settingsOpen,setSettingsOpen]=useState(false),[settings,setSettings]=useState<Record<string,number>>({}),[historyOpen,setHistoryOpen]=useState(false),[history,setHistory]=useState<Snapshot[]>([]),[historyIndex,setHistoryIndex]=useState<number|null>(null);
 const [auth,setAuth]=useState<{role:string;demo:boolean}|null>(null),[loginNeeded,setLoginNeeded]=useState(false),[fatal,setFatal]=useState(''),[busy,setBusy]=useState(false),[stale,setStale]=useState(false);
 const view=historyIndex!==null?history[historyIndex]||snapshot:snapshot;
 const historical=historyIndex!==null;
 const canControl=!!auth&&auth.role!=='viewer'&&!historical&&connected&&!stale;
 const selectedTrain=view?.trains.find(t=>t.id===selected);
 const loadPlans=useCallback(async()=>{const data=await api<{plans:Plan[];baseline:Plan}>('/plans');setPlans(data.plans);setBaseline(data.baseline);},[]);
 const refresh=useCallback(async()=>{setSnapshot(await api<Snapshot>('/state'));await loadPlans();},[setSnapshot,loadPlans]);
 useEffect(()=>{api<{role:string;demo:boolean}>('/auth/me').then(setAuth).catch(()=>setLoginNeeded(true));},[]);
 useEffect(()=>{
  if(!auth)return;
  let stopped=false,ws:WebSocket|null=null,retry:ReturnType<typeof setTimeout>|undefined,sequence=0;
  const connect=()=>{
   if(stopped)return;
   ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);
   ws.onopen=()=>{if(stopped)return;setConnected(true);refresh().catch(e=>setFatal(e.message));};
   ws.onmessage=event=>{if(stopped)return;const data=JSON.parse(event.data);if(sequence&&data.seq>sequence+1)refresh().catch(()=>{});sequence=data.seq;
    if(data.type==='state.updated'){paintEvent.current={seq:data.seq,ws:ws!,received:performance.now()};setSnapshot(data.payload);}
    if(['replan.completed','plan.applied','simulation.changed'].includes(data.type)){loadPlans().catch(()=>{});if(data.type==='plan.applied')setPreview(null);}
    if(data.type==='incident.created')setPreview(null);
    if(data.type==='replan.failed')message.warning(data.payload.message||'Допустимый план не найден');
   };
   ws.onclose=()=>{setConnected(false);if(stopped)return;fetch('/api/auth/me').then(r=>{if(stopped)return;if(r.status===401){setAuth(null);setLoginNeeded(true);message.warning('Сессия завершилась. Войдите повторно.');}else retry=setTimeout(connect,2000);}).catch(()=>{if(!stopped)retry=setTimeout(connect,2000);});};
   ws.onerror=()=>ws?.close();
  };
  Promise.all([api<Topology>('/topology').then(setTopology),refresh()]).then(connect).catch(e=>setFatal(e.message));
  return()=>{stopped=true;clearTimeout(retry);ws?.close();};
 },[auth,refresh,loadPlans,setSnapshot,setConnected,message]);
 useEffect(()=>{
  const pending=paintEvent.current;if(!pending)return;
  let second=0;const first=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>{
   if(document.visibilityState==='visible'&&pending.ws.readyState===WebSocket.OPEN)
    pending.ws.send(JSON.stringify({type:'paint.ack',seq:pending.seq,render_ms:performance.now()-pending.received}));
  });});return()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);};
 },[snapshot]);
 useEffect(()=>{if(auth)api<{engine:string;scenarios:string[]}>('/logic/scenarios').then(d=>setLogicCases(d.engine==='logic'?d.scenarios:[])).catch(()=>{});},[auth]);
 useEffect(()=>{if(view?.trains.length&&!view.trains.some(t=>t.id===selected))select(view.trains[0].id);},[view,selected,select]);
 useEffect(()=>{if(topology)setIncidentTarget(topology.sections[0].id);},[topology]);
 useEffect(()=>{const timer=setInterval(()=>setStale(Date.now()-lastUpdate>5000),1000);return()=>clearInterval(timer);},[lastUpdate]);
 useEffect(()=>{let cancelled=false;setProfile(null);if(auth&&!historical)api<Profile>(`/trains/${selected}/profile`).then(p=>{if(!cancelled)setProfile(p);}).catch(()=>{});return()=>{cancelled=true;};},[selected,snapshot?.active_plan_id,auth,historical]);
 const action=async(path:string,body?:unknown)=>{setBusy(true);try{await api(path,'POST',body);await refresh();}catch(e){message.error((e as Error).message);}finally{setBusy(false);}};
 const openHistory=async()=>{try{const items=await api<Snapshot[]>(`/history?from=${Math.max(0,(snapshot?.sim_time_s||0)-900)}`);setHistory(items);setHistoryOpen(true);}catch(e){message.error((e as Error).message);}};
 const openSettings=async()=>{try{setSettings(await api<Record<string,number>>('/settings'));setSettingsOpen(true);}catch(e){message.error((e as Error).message);}};
 const createIncident=async()=>{setBusy(true);try{await api('/incidents','POST',{kind:incidentKind,target_id:incidentTarget,duration_s:duration*60});setIncidentOpen(false);setPlans([]);await refresh();message.success('Сбой зарегистрирован. Новые отправления удерживаются до применения плана.');}catch(e){message.error((e as Error).message);}finally{setBusy(false);}};
 const changeIncidentKind=(kind:string)=>{setIncidentKind(kind);setIncidentTarget(kind==='delay'?view?.trains.find(t=>t.status==='waiting')?.id||'':topology?.sections[0]?.id||'');};

 if(loginNeeded)return <div className="auth-screen"><div className="auth-card"><TrainFront size={40}/><h1>RailFlow</h1><p>Вход в диспетчерский центр</p><Form layout="vertical" initialValues={{role:'viewer'}} onFinish={async values=>{try{await api('/auth/login','POST',values);setAuth(await api('/auth/me'));setLoginNeeded(false);}catch(e){message.error((e as Error).message);}}}><Form.Item name="role" label="Роль"><Select options={[{value:'viewer',label:'Наблюдатель'},{value:'dispatcher',label:'Диспетчер'},{value:'admin',label:'Администратор'}]}/></Form.Item><Form.Item name="password" label="Пароль" rules={[{required:true}]}><Input.Password/></Form.Item><Button htmlType="submit" type="primary" block>Войти</Button></Form></div></div>;
 if(!view||!topology)return <div className="loading"><TrainFront size={44}/><h2>RailFlow</h2><Spin/><p>{fatal||'Подготавливаем участок Астана — Кокшетау…'}</p>{fatal&&<Button onClick={()=>location.reload()}>Повторить подключение</Button>}</div>;
 const activeIncidents=view.incidents.filter(i=>i.end_s>view.sim_time_s);
 const moving=view.trains.filter(t=>t.status==='moving').length;
 return <div className="shell">
  <aside className="rail"><a className="brand-icon" href="#" aria-label="RailFlow"><TrainFront size={27}/></a><Tooltip title="Диспетчерская" placement="right"><button className="rail-button active" aria-label="Диспетчерская" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><LayoutDashboard size={21}/></button></Tooltip><Tooltip title="Карта сети" placement="right"><button className="rail-button" aria-label="Карта сети" onClick={()=>{setMapTab('map');setAllCountry(v=>!v);}}><Waypoints size={22}/></button></Tooltip><Tooltip title="История" placement="right"><button className="rail-button" aria-label="История" onClick={openHistory}><History size={22}/></button></Tooltip><div className="rail-bottom"><Tooltip title="Настройки" placement="right"><button className="rail-button" aria-label="Настройки" onClick={openSettings}><Settings2 size={21}/></button></Tooltip><span className="avatar">ДЦ</span></div></aside>
  <div className="workspace">
   <header className="topbar"><div className="wordmark">RailFlow<span>ДИСПЕТЧЕРСКИЙ ЦЕНТР</span></div><div className="breadcrumb">Казахстан <ChevronRight size={13}/> Северный участок</div><div className="connection"><span className={`dot ${connected&&!stale?'green':'red'}`}/>{connected&&!stale?'Поток подключён':'Данные устарели'}<span className="update-time">{lastUpdate?new Date(lastUpdate).toLocaleTimeString('ru'):''}</span></div><span className="demo-tag">{auth?.demo?'ДЕМО-СРЕДА':auth?.role}</span>{!auth?.demo&&<Button size="small" onClick={()=>api('/auth/logout','POST').then(()=>location.reload())}>Выйти</Button>}</header>
   <main>
    <section className="page-heading"><div><div className="eyebrow"><span className="mini-line"/> УПРАВЛЕНИЕ ДВИЖЕНИЕМ</div><h1>Астана <span className="title-arrow">↗</span> Кокшетау</h1><p>{topology.stations.length} станций <span>·</span> {(topology.length_m/1000).toFixed(1)} км <span>·</span> {topology.engine==='logic'?'Многопутная модель · logic':'Однопутный демосценарий'}</p></div><div className="heading-actions"><Button icon={<ArrowDownToLine size={15}/>} href="/api/report.csv" disabled={historical}>Экспорт CSV</Button><Button icon={<History size={15}/>} onClick={openHistory}>История</Button><span className="date-pill"><Clock3 size={15}/> {clock(view.sim_time_s)} <small>время модели</small></span></div></section>
    {(historical||view.awaiting_plan||!connected||stale)&&<div className={`notice ${historical?'history-notice':''}`}><TriangleAlert size={16}/>{historical?'Просмотр истории — текущая симуляция продолжает работать':!connected||stale?'Нет свежих данных. Переподключение выполняется автоматически.':'Движение удерживается. Рассчитайте и примените допустимый план.'}{historical&&<Button size="small" onClick={()=>{setHistoryIndex(null);setPreview(null);}}>Вернуться в эфир</Button>}</div>}
    {logicCases.length>0&&<section className="control-bar"><span>Сценарии logic</span><Select aria-label="Сценарий logic" style={{width:260,maxWidth:'100%'}} value={logicCase} onChange={setLogicCase} options={logicCases.map(value=>({value,label:value.replaceAll('_',' ')}))}/><Button disabled={!canControl||view.replanning} onClick={()=>modal.confirm({title:'Загрузить сценарий?',content:'Начнётся новый запуск с заданным сбоем. История останется в базе.',onOk:()=>action(`/logic/scenarios/${logicCase}`).then(()=>{setPreview(null);setHistoryIndex(null);})})}>Загрузить и рассчитать</Button><Button href="/api/logic/diagnostics" target="_blank">Пути и метрики (JSON)</Button></section>}
    <section className="metrics-grid">
     <div className="metric featured"><div className="metric-label">Индекс движения <Activity size={17}/></div><div className="metric-value">{view.metrics.index?.toFixed(1)??"—"}<span>/ 100</span></div><div className="metric-foot"><span className={`dot ${view.metrics.category==='Критично'?'red':view.metrics.category==='Внимание'?'amber':view.metrics.index===null?'gray':'green'}`}/> {view.metrics.category||'Индекс'} · {view.metrics.provisional?'Предварительно · ещё нет прибытий':'Фактические показатели'}</div><div className="meter"><i style={{width:`${view.metrics.index??0}%`}}/></div></div>
     <div className="metric"><div className="metric-label">Поезда на участке <TrainFront size={17}/></div><div className="metric-value">{view.trains.filter(t=>t.on_network!==false).length}<span>из {view.trains.length} поездов</span></div><div className="metric-foot"><b>{moving}</b> в движении <span className="divider">/</span> {view.metrics.completed_trips} завершили маршрут</div></div>
     <div className="metric"><div className="metric-label">Суммарная задержка <Clock3 size={17}/></div><div className="metric-value">{(view.metrics.total_delay_s/60).toFixed(1)}<span>мин</span></div><div className="metric-foot">Максимальная <b>{minutes(view.metrics.max_delay_s)}</b></div></div>
     <div className="metric"><div className="metric-label">Расход энергии <Zap size={17}/></div><div className="metric-value">{(view.metrics.energy_kwh/1000).toFixed(2)}<span>МВт·ч</span></div><div className="metric-foot">{view.engine==='logic'?'Тяга и питание · движение и ожидание':'Расчётная модель тяги · без рекуперации'}</div></div>
    </section>
    {view.metrics.components&&<details className="secondary-metrics"><summary>Пять составляющих индекса</summary>{Object.entries(view.metrics.components).map(([key,value])=><span key={key}>{metricLabels[key]}: <b>{value===null?'нет данных':`${(value*100).toFixed(1)}%`}</b>{view.metrics.contributions?.[key]!=null?` · вклад ${view.metrics.contributions[key]!.toFixed(1)} п.`:''} </span>)}</details>}
    <div className="secondary-metrics"><span>Конфликты <b>{view.metrics.conflicts}</b></span><span>Точность прибытия <b>{view.metrics.on_time_pct===null?'Нет прибытий':`${view.metrics.on_time_pct}%`}</b></span><span>Взвешенная задержка <b>{minutes(view.metrics.weighted_delay_s)}</b></span><span>Завершено к текущему времени <b>{view.metrics.completed_trips} / {view.metrics.scheduled_trips}</b></span></div>
    <section className="control-bar"><div className="run-status"><span className={`dot ${view.running?'green':'gray'}`}/>{view.decision_hold?'Ожидание решения · часы остановлены':view.running?'Симуляция запущена':'Симуляция на паузе'}</div><div className="control-buttons"><Button type="primary" disabled={!canControl} loading={busy} icon={view.running?<Pause size={15}/>:<Play size={15}/>} onClick={()=>action(`/simulation/${view.running?'pause':'start'}`)}>{view.running?'Пауза':'Запустить'}</Button><Tooltip title="Воспроизводимый сброс"><Button aria-label="Сбросить симуляцию" disabled={!canControl||view.replanning} icon={<RotateCcw size={16}/>} onClick={()=>modal.confirm({title:'Сбросить сценарий?',content:'Движение вернётся к исходному состоянию. События сохранятся в базе.',okText:'Сбросить',cancelText:'Отмена',onOk:()=>action('/simulation/reset').then(()=>{setPreview(null);setHistoryIndex(null);})})}/></Tooltip><span className="speed-label">Скорость</span><Select aria-label="Скорость симуляции" value={view.speed} disabled={!canControl} onChange={multiplier=>action('/simulation/speed',{multiplier})} options={[1,5,15,30,60].map(x=>({value:x,label:`${x}×`}))}/></div><div className="control-right"><span className="safe-label"><ShieldCheck size={15}/> Независимая проверка планов</span><Button disabled={!canControl} icon={<TriangleAlert size={15}/>} onClick={()=>setIncidentOpen(true)}>Добавить сбой</Button></div></section>
    <div className="primary-grid"><div className="left-stack">
     <section className="panel map-panel"><div className="panel-heading"><div className="panel-title"><MapPin size={17}/><h2>Карта движения</h2><span className="live-badge">{historical?'АРХИВ':'LIVE'}</span></div><div className="tab-buttons"><button className={mapTab==='map'?'on':''} onClick={()=>setMapTab('map')}>География</button><button className={mapTab==='scheme'?'on':''} onClick={()=>setMapTab('scheme')}>Схема путей</button></div></div><Timeline live={snapshot!} canControl={canControl} onView={s=>{setPreview(null);if(s){setHistory([s]);setHistoryIndex(0);}else setHistoryIndex(null);}}/><div className="map-toolbar"><span>Пунктир — пути модели · цвета — назначение путей OSM</span>{mapTab==='map'&&<button onClick={()=>setAllCountry(x=>!x)}>{allCountry?'К маршруту':'Весь Казахстан'} <ArrowRight size={13}/></button>}</div>{mapTab==='map'?<RailMap topology={topology} snapshot={view} allCountry={allCountry}/>:<TrackDiagram topology={topology} snapshot={view}/>}<div className="map-footer"><span><span className="dot green"/> Пассажирский</span><span><span className="dot amber"/> Грузовой</span><span><span className="dot red"/> Закрытие / запрет</span><span className="map-model">Геометрия OSM · инфраструктура демо</span></div></section>
     <section className="panel diagram-panel"><div className="panel-heading"><div className="panel-title"><GitBranch size={17}/><h2>График движения</h2></div><div className="chart-legend"><span>┄ Исходный</span><span>━ {preview?'Предлагаемый':'Активный'}</span></div></div><TrainChart topology={topology} snapshot={view} baseline={historical?null:baseline} preview={historical?null:preview}/>{preview&&<div className="preview-banner">Предпросмотр: {preview.label}<button onClick={()=>setPreview(null)}>Вернуться к активному</button></div>}</section>
    </div><aside className="right-stack">{view.engine==='logic'&&!historical&&<DispatchPolicy snapshot={view} topology={topology} selected={selected} disabled={!canControl||view.replanning}/>}{view.engine==='logic'&&<FleetEditor key={view.epoch} snapshot={view} disabled={!canControl||view.replanning||view.awaiting_plan} onApplied={refresh}/>}
     <section className="panel fleet-panel"><div className="panel-heading"><div className="panel-title"><TrainFront size={17}/><h2>Поезда</h2></div><span className="count-badge">{view.trains.length}</span></div><div className="fleet-list">{view.trains.map(train=><button key={train.id} title={train.wait_reason||undefined} className={`train-row ${selected===train.id?'selected':''}`} onClick={()=>select(train.id)}><span className={`train-icon ${train.type}`}><TrainFront size={17}/></span><span className="train-ident"><strong>№ {train.number} <small>{train.direction>0?'↗':'↙'}</small></strong><span>{train.type==='passenger'?'Пассажирский':'Грузовой'}</span></span><span className="train-speed"><strong>{(train.speed_mps*3.6).toFixed(0)} <small>км/ч</small></strong><span className={train.delay_s?'late':''}>{train.delay_s?`+${minutes(train.delay_s)}`:statusName[train.status]}</span></span><ChevronRight size={13}/></button>)}</div></section>
     <section className="panel detail-panel"><div className="panel-heading"><div className="panel-title"><h2>Поезд № {selectedTrain?.number}</h2></div><Tag color="cyan">{selectedTrain&&statusName[selectedTrain.status]}</Tag></div><div className="detail-grid"><div><span>Направление</span><strong>{topology.stations.find(s=>s.id===selectedTrain?.destination)?.name||(selectedTrain?.direction===1?'Кокшетау-1':'Астана-1')}</strong></div><div><span>Прибытие по плану</span><strong>{selectedTrain?.eta_s!=null?clock(selectedTrain.eta_s).slice(0,-3):'Ожидает плана'}</strong></div><div><span>Масса / длина</span><strong>{(selectedTrain?.mass_kg||0)/1000} т / {selectedTrain?.length_m} м</strong></div><div><span>Пройдено</span><strong>{((selectedTrain?.distance_travelled_m??(selectedTrain?.direction===1?selectedTrain.position_m:topology.length_m-(selectedTrain?.position_m||0)))/1000).toFixed(1)} км</strong></div></div><div className="dispatch-wait"><strong>{selectedTrain?.station_track_id?`Станционный путь ${selectedTrain.station_track_id}`:selectedTrain?.main_track_id?`Главный путь ${selectedTrain.main_track_id}`:selectedTrain?.status==='completed'?'Рейс завершён':'Вне участка'}</strong>{selectedTrain?.wait_reason}{selectedTrain?.next_departure_s!=null&&<div>Следующее отправление: {clock(selectedTrain.next_departure_s)}</div>}</div><div className="profile-label"><span>Профиль скорости</span><small>км/ч · ┄ ограничение</small></div>{historical?<div className="empty small">В архиве: {((selectedTrain?.speed_mps||0)*3.6).toFixed(1)} км/ч в {clock(view.sim_time_s)}. Расчётный профиль доступен в эфире.</div>:<SpeedChart profile={profile?.reachable&&view.plan.applicable!==false&&!view.awaiting_plan?profile:null}/>}<div className="detail-foot"><Zap size={13}/> Прогноз рейса: {profile?.reachable&&view.plan.applicable!==false&&!view.awaiting_plan&&!historical?(profile.energy_kwh/1000).toFixed(2):'—'} МВт·ч</div></section>
    </aside></div>
    <section className="panel recommendation-panel"><div className="panel-heading"><div className="panel-title"><Command size={17}/><h2>Варианты перепланирования</h2><span className="subtle">Прогноз, не фактический результат</span></div><Button disabled={!canControl||view.replanning} loading={view.replanning} icon={<RotateCcw size={14}/>} onClick={()=>action('/replan')}>{view.replanning?'Расчёт…':'Рассчитать варианты'}</Button></div>{plans.length&&!historical?<div className="plan-grid">{plans.map(plan=><article key={plan.id} className={`plan-card ${preview?.id===plan.id?'chosen':''}`}><div className="plan-top"><span className="plan-check"><Check size={17}/></span><div><h3>{plan.label}</h3><p>{plan.status==='optimal'?'Оптимальность доказана':plan.status==='heuristic'?'Резервная эвристика':'Допустимый план · оптимальность не доказана'}</p></div><span className="plan-time">{plan.calculation_s.toFixed(2)} с{!plan.within_budget?' · бюджет превышен':''}</span></div><details className="plan-reason"><summary>Обоснование и ограничения</summary><p>{plan.reason}</p></details><div className="plan-stats"><div><span>Суммарная</span><strong>{minutes(plan.metrics.total_delay_s)}</strong></div><div><span>Максимальная</span><strong>{minutes(plan.metrics.max_delay_s)}</strong></div><div><span>Пассажирские</span><strong>{minutes(plan.metrics.passenger_delay_s)}</strong></div><div><span>Энергия</span><strong>{(plan.metrics.energy_kwh/1000).toFixed(2)} МВт·ч</strong></div></div><div className="plan-change">Индекс прогноза: {plan.metrics.index?.toFixed(1)??"—"} <span>{view.plan.applicable===false?'Прежний план требует пересчёта':`Δ ${((plan.metrics.index??0)-(view.plan.metrics.index??0)).toFixed(1)} к активному плану`}</span></div><div className="plan-actions"><Button onClick={()=>setPreview(plan)}>Сравнить график</Button><Button type="primary" disabled={!canControl} onClick={()=>action(`/plans/${plan.id}/apply`)}>Применить <ArrowRight size={13}/></Button></div></article>)}</div>:<div className="recommendation-empty"><span className="empty-icon"><GitBranch size={24}/></span><div><h3>{view.replanning?'Ищем допустимые варианты движения…':'Движение начинается с плана'}</h3><p>{historical?'Вернитесь в эфир для работы с рекомендациями.':'Добавьте сбой или запустите расчёт, чтобы сравнить баланс задержек и приоритет пассажирских поездов.'}</p></div><span className="budget-pill">CP-SAT · бюджет цикла 5 с</span></div>}</section>
    <section className="events-strip"><div><Radio size={16}/><strong>События участка</strong><span>{activeIncidents.length} активных</span></div>{activeIncidents.length?activeIncidents.map(i=><span className="event-pill" key={i.id}><span className="dot amber"/>{incidentName[i.kind]} · {i.target_id} · до {clock(i.end_s).slice(0,-3)}</span>):<span className="subtle">Активных сбоев нет. Участок готов к работе.</span>}</section>
    <footer className="footer"><span>RailFlow / KTZH · Учебный диспетчерский симулятор</span><span>© OpenStreetMap contributors · ODbL <span className="divider">/</span> v0.1</span></footer>
   </main>
  </div>
  <Modal title="Добавить сбой" open={incidentOpen} onCancel={()=>setIncidentOpen(false)} onOk={createIncident} confirmLoading={busy} okText="Добавить и пересчитать" cancelText="Отмена" okButtonProps={{disabled:!incidentTarget||!canControl}}><div className="modal-fields"><label>Тип события<Select value={incidentKind} onChange={changeIncidentKind} options={Object.entries(incidentName).filter(([k])=>k!=='speed_restriction'||view.engine==='logic').map(([value,label])=>({value,label}))}/></label><label>{incidentKind==='delay'?'Поезд на станции':'Перегон'}<Select value={incidentTarget||undefined} onChange={setIncidentTarget} options={incidentKind==='delay'?view.trains.filter(t=>t.status==='waiting').map(t=>({value:t.id,label:`№ ${t.number}`})):topology.sections.map((s,i)=>({value:s.id,label:`${topology.stations[i].name} — ${topology.stations[i+1].name}`}))}/></label><label>Длительность, минут<InputNumber value={duration} min={1} max={120} onChange={n=>setDuration(n||10)}/></label><p className="subtle">{view.engine==='logic'?'Во время расчёта и ожидания решения часы модели остановлены. Закрытие действует после освобождения перегона уже вошедшими поездами.':'Поезда, уже вошедшие на перегон, освобождают его. Новые отправления удерживаются до применения проверенного плана.'}</p></div></Modal>
  <Drawer title="История · последние 15 минут модели" open={historyOpen} onClose={()=>setHistoryOpen(false)} width={460}><p>Выбор снимка меняет только просмотр. Управление движением в архиве отключено.</p>{history.length?<><Slider min={0} max={history.length-1} value={historyIndex??history.length-1} onChange={index=>{setHistoryIndex(index);setPreview(null);}} tooltip={{formatter:index=>clock(history[index||0]?.sim_time_s||0)}}/><div className="history-time">{clock(history[historyIndex??history.length-1].sim_time_s)}</div><Button type="primary" onClick={()=>{setHistoryIndex(null);setHistoryOpen(false);}}>Вернуться в прямой эфир</Button><p className="subtle">{history.length} сохранённых снимков. При ускорении интервал между ними увеличивается.</p></>:<div className="empty">Снимков ещё нет.</div>}</Drawer>
  <Drawer title="Настройки сценария" open={settingsOpen} onClose={()=>setSettingsOpen(false)} width={440}><Tag color="gold">Демонстрационные допущения</Tag><ul className="assumptions">{topology.assumptions.map((text,i)=><li key={i}>{text}</li>)}</ul><h3>Веса и нормирование</h3><div className="modal-fields">{Object.entries({passenger_weight:'Вес пассажирских',freight_weight:'Вес грузовых',delay_weight:'Вес задержки в индексе',energy_weight:'Вес энергии в индексе',delay_norm_s:'Норма задержки, с',energy_norm_kwh:'Норма энергии, кВт·ч',arrival_tolerance_s:'Допуск прибытия, с'}).filter(([key])=>view.engine!=='logic'||['passenger_weight','freight_weight'].includes(key)).map(([key,label])=><label key={key}>{label}<InputNumber disabled={auth?.role!=='admin'||historical} value={settings[key]} onChange={n=>setSettings(s=>({...s,[key]:n??0}))}/></label>)}</div><Button type="primary" disabled={auth?.role!=='admin'||historical} onClick={async()=>{try{await api('/settings','PUT',settings);setSettingsOpen(false);setPlans([]);message.success('Настройки сохранены. Пересчитайте варианты.');}catch(e){message.error((e as Error).message);}}}>Сохранить настройки</Button><p className="subtle">Пороговые значения одинаковы для сравниваемых планов. Изменение настроек сбрасывает рассчитанные варианты.</p>{view.engine==='logic'&&settingsOpen&&<MetricSettings disabled={auth?.role!=='admin'||historical||view.replanning} onSaved={()=>{setPlans([]);refresh().catch(()=>{});}}/>}</Drawer>
 </div>;
}
