import {useEffect,useState} from 'react';
import {App,Button,InputNumber,Select} from 'antd';
import {api} from './store';
import type {Snapshot,Topology} from './types';
type Choices={station_tracks:Record<string,string>;main_tracks:Record<string,string>};
type Policy={epoch:string;wear:Record<string,{wear_pct:number}>;assignments:Record<string,Choices>;assumption:string};
export function DispatchPolicy({snapshot,topology,selected,disabled}:{snapshot:Snapshot;topology:Topology;selected:string;disabled:boolean}){
 const {message}=App.useApp();const [policy,setPolicy]=useState<Policy|null>(null),[draft,setDraft]=useState<Choices>({station_tracks:{},main_tracks:{}}),[resource,setResource]=useState(''),[wear,setWear]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;setPolicy(null);setError('');api<Policy>('/dispatch/policy').then(p=>{if(!cancelled)setPolicy(p);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[snapshot.epoch,snapshot.active_plan_id,snapshot.awaiting_plan]);
 useEffect(()=>{setDraft(policy?.assignments[selected]||{station_tracks:{},main_tracks:{}});},[selected,policy]);
 useEffect(()=>{setWear(policy?.wear[resource]?.wear_pct??null);},[resource,policy]);
 const train=snapshot.trains.find(t=>t.id===selected),route=train?.route||[];
 const stationName=(id:string)=>topology.stations.find(s=>s.id===id)?.name||id;
 const save=async(path:string,body:object)=>{setBusy(true);try{await api('/dispatch/'+path,'POST',{epoch:snapshot.epoch,...body});setPolicy(await api<Policy>('/dispatch/policy'));message.success('Сохранено. Выберите и примените проверенный план ниже.');}catch(e){message.error((e as Error).message);}finally{setBusy(false);}};
 const choose=(group:keyof Choices,id:string,value:string)=>setDraft(old=>{const next={...old,[group]:{...old[group]}};if(value)next[group][id]=value;else delete next[group][id];return next;});
 const resources=[...topology.stations.flatMap(s=>(s.track_layout||[]).map(t=>({value:`track:${s.id}:${t.id}`,label:`${s.name} · ${t.id}`}))),...topology.sections.flatMap(s=>(s.main_tracks||[]).map(t=>({value:`main_track:${s.id}:${t.id}`,label:`${stationName(s.from_station)} — ${stationName(s.to_station)} · путь ${t.id}`})))];
 const control=async(path:string,body:object)=>{setBusy(true);try{await api('/control/'+path,'POST',{epoch:snapshot.epoch,...body});message.success('Управление обновлено');}catch(e){message.error((e as Error).message);}finally{setBusy(false);}};
 const next=(snapshot.pending_departures||[]).filter(m=>m.train_id===selected).sort((a,b)=>a.start_s-b.start_s)[0];
 return <section className="panel dispatch-policy"><h3>Режим управления</h3><Select aria-label="Режим управления" disabled={disabled||busy} value={snapshot.control_mode||'manual'} onChange={mode=>control('mode',{mode})} options={[{value:'manual',label:'Ручной — маршрут и разрешение диспетчера'},{value:'automatic',label:'Автоматический — проверка и применение системой'}]}/><p>{snapshot.control_mode==='automatic'?'Система выбирает проверенный вариант после изменения условий. При отсутствии допустимого плана движение удерживается.':'Укажите пути ниже, примените проверенный план и разрешите отправление. Перед неразрешённым отправлением часы модели остановятся для решения диспетчера.'}</p>{snapshot.control_mode!=='automatic'&&next&&<Button disabled={disabled||busy||snapshot.awaiting_plan||next.authorized} onClick={()=>control('authorize',{plan_id:snapshot.active_plan_id,train_id:selected,section_id:next.section_id})}>{next.authorized?'Маршрут разрешён':`Разрешить ${stationName(next.origin||'')} → ${stationName(next.destination||'')} · путь ${next.main_track_id}`}</Button>}<h3>Назначение путей · {train?.number}</h3>{error&&<p role="alert">{error}</p>}<label>Категория и приоритет (правило симуляции)<Select disabled={disabled||busy||!train} value={train?.dispatch_category||train?.type} onChange={category=>save('category',{train_id:selected,category})} options={[{value:'emergency',label:'1 · Аварийный / особого назначения'},{value:'passenger',label:'2 · Пассажирский'},{value:'express_freight',label:'3 · Ускоренный грузовой'},{value:'freight',label:'4 · Обычный грузовой'},{value:'service',label:'5 · Хозяйственный / локомотив'}]}/></label><p>Категория повышает вес задержки в оптимизации. Занятый путь и замкнутая стрелка сохраняют запрет для всех категорий.</p><p>«Авто» выбирает доступный путь. Ручное назначение обязательно для планировщика. Выполненные движения и подходы сохраняются.</p><details><summary>Пути выбранного поезда</summary><div className="policy-routes">
 {route.map(sid=>{const station=topology.stations.find(s=>s.id===sid);const stop=snapshot.plan.stops?.find(s=>s.train_id===selected&&s.station_id===sid);const incoming=snapshot.plan.movements.find(m=>m.train_id===selected&&m.destination===sid&&m.start_s<=snapshot.sim_time_s);const locked=(stop?.arrival_s??Infinity)<=snapshot.sim_time_s||!!incoming;return <label key={sid}>{stationName(sid)}{locked&&<small>Зафиксировано: {stop?.track_id}</small>}<Select disabled={disabled||busy||locked||!policy} value={draft.station_tracks[sid]||''} onChange={v=>choose('station_tracks',sid,v)} options={[{value:'',label:'Авто'},...(station?.track_layout||[]).map(t=>({value:t.id,label:`Путь ${t.id}`}))]}/></label>;})}
 {topology.sections.filter(s=>route.includes(s.from_station)&&route.includes(s.to_station)).map(s=>{const direction=route.indexOf(s.from_station)<route.indexOf(s.to_station)?'a_to_b':'b_to_a';const m=snapshot.plan.movements.find(m=>m.train_id===selected&&m.section_id===s.id);return <label key={s.id}>{stationName(s.from_station)} — {stationName(s.to_station)}<Select disabled={disabled||busy||!policy||(m?.start_s??Infinity)<=snapshot.sim_time_s} value={draft.main_tracks[s.id]||''} onChange={v=>choose('main_tracks',s.id,v)} options={[{value:'',label:'Авто'},...(s.main_tracks||[]).filter(t=>t.direction==='both'||t.direction===direction).map(t=>({value:t.id,label:`Главный ${t.id}`}))]}/></label>;})}
 </div></details><div className="policy-actions"><Button disabled={disabled||busy||!policy} onClick={()=>save('assignment',{train_id:selected,station_tracks:{},main_tracks:{}})}>Всё «Авто» для поезда</Button><Button type="primary" loading={busy} disabled={disabled||!policy} onClick={()=>save('assignment',{train_id:selected,...draft})}>Назначить</Button></div>
 <h3>Износ пути · учебная оценка</h3><Select aria-label="Путь для оценки износа" showSearch optionFilterProp="label" placeholder="Выберите путь" value={resource||undefined} onChange={setResource} options={resources}/><label>Индекс износа, %<InputNumber aria-label="Учебный индекс износа" min={0} max={100} precision={0} value={wear} onChange={setWear} placeholder="Нет данных"/></label><Button disabled={disabled||busy||!resource||!policy} onClick={()=>save('condition',{resource,wear_pct:wear})}>Сохранить и пересчитать</Button><p>{policy?.assumption||'Реальные результаты обследования не предоставлены. Пустое значение означает «нет данных».'}</p><p>Ограничения начнут действовать после сохранения; часы остановятся до применения плана. При закрытии учитывается освобождение пути уже вошедшими поездами.</p>
 </section>;
}
