import {useState} from 'react';
import {App,Button,InputNumber,Select} from 'antd';
import {api} from './store';
import type {Snapshot,Topology} from './types';
type Addition={origin?:string;destination?:string;kind:'passenger'|'freight';direction:1|-1;ready_in_s:number;dispatch_category:string};
export function FleetEditor({snapshot,topology,disabled,onApplied}:{snapshot:Snapshot;topology:Topology;disabled:boolean;onApplied:()=>Promise<void>}){
 const {message}=App.useApp();
 const [origin,setOrigin]=useState(topology.stations[0].id),[destination,setDestination]=useState(topology.stations.at(-1)!.id);
 const [add,setAdd]=useState<Addition[]>([]),[kind,setKind]=useState<Addition['kind']>('passenger'),[direction,setDirection]=useState<1|-1>(1),[category,setCategory]=useState('passenger'),[minutes,setMinutes]=useState(2),[busy,setBusy]=useState(false);
 const apply=async()=>{setBusy(true);try{await api('/fleet/batch','POST',{epoch:snapshot.epoch,add,remove:[]});setAdd([]);await onApplied();message.success('Состав и расписание обновлены');}catch(e){message.error((e as Error).message);}finally{setBusy(false);}};
 return <section className="panel fleet-editor"><h3>Управление поездами</h3><label>Тип<Select value={kind} onChange={v=>{setKind(v);setCategory(v);}} options={[{value:'passenger',label:'Пассажирский'},{value:'freight',label:'Грузовой'}]}/></label>{topology.network?<><label>Откуда<Select showSearch optionFilterProp="label" value={origin} onChange={setOrigin} options={topology.stations.map(s=>({value:s.id,label:s.name}))}/></label><label>Куда<Select showSearch optionFilterProp="label" value={destination} onChange={setDestination} options={topology.stations.map(s=>({value:s.id,label:s.name}))}/></label></>:<label>Направление<Select value={direction} onChange={setDirection} options={[{value:1,label:`${topology.stations[0].name} → ${topology.stations.at(-1)?.name}`},{value:-1,label:`${topology.stations.at(-1)?.name} → ${topology.stations[0].name}`}]}/></label>}<label>Приоритет<Select value={category} onChange={setCategory} options={[{value:"emergency",label:"1 · Аварийный"},{value:"passenger",label:"2 · Пассажирский"},{value:"express_freight",label:"3 · Ускоренный грузовой"},{value:"freight",label:"4 · Грузовой"},{value:"service",label:"5 · Хозяйственный"}]}/></label><label>Готовность через, мин<InputNumber precision={0} min={1} max={240} value={minutes} onChange={v=>setMinutes(v||1)}/></label><Button disabled={disabled||busy||add.length>=5} onClick={()=>setAdd(a=>[...a,{kind,direction,ready_in_s:minutes*60,dispatch_category:category,...(topology.network?{origin,destination}:{})}])}>＋ Добавить в пакет</Button>
 <div className="fleet-staged">{add.map((a,i)=><div key={i}>{a.kind==='passenger'?'Пассажирский':'Грузовой'} {a.origin?`${topology.stations.find(s=>s.id===a.origin)?.name} → ${topology.stations.find(s=>s.id===a.destination)?.name}`:a.direction===1?`→ ${topology.stations.at(-1)?.name}`:`→ ${topology.stations[0].name}`} <button disabled={busy} aria-label={`Отменить добавление ${i+1}`} onClick={()=>setAdd(x=>x.filter((_,j)=>i!==j))}>×</button></div>)}</div>
 <Button type="primary" block disabled={disabled||!add.length} loading={busy} onClick={apply}>Добавить: {add.length}</Button><p>Пакет применяется целиком после проверки путей. В отдельном коридоре до 20 поездов, в общей сети до 120. Удаление поездов отключено. Завершённые рейсы остаются в списке и истории.</p></section>;
}
