import {useState} from 'react';
import {Button,Select} from 'antd';
import {api} from './store';
type Station={id:string;name:string;observed_ways:{osm_way_id:number;reference_tag:string|null;service:string|null;geometry_length_within_500m_m:number}[]};
type Catalog={stations:Station[];coverage:{station_count:number;regional_station_count:number;reachable_directed_pairs:number;skipped:{name:string;reason:string}[]};source:{boundary_year:number;osm_timestamp:string}};
export function InfrastructureInventory(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[station,setStation]=useState(''),[error,setError]=useState('');
 return <details className="panel" style={{padding:14}}><summary>Источники и полнота инфраструктуры</summary><p>Рабочие номера, полезные длины путей и маршруты стрелок требуют схем владельца инфраструктуры. Фрагменты OSM не определяют эксплуатационную вместимость.</p><Button onClick={()=>api<Catalog>('/logic/regional-catalog').then(c=>{setCatalog(c);setStation(c.stations[0].id);setError('');}).catch(e=>setError(e.message))}>Показать наблюдения карты</Button>{error&&<p role="alert">{error}</p>}{catalog&&<><p>{catalog.coverage.regional_station_count} станций в архивной границе области и Астаны, {catalog.coverage.station_count} с подходами. Граница: {catalog.source.boundary_year}; OSM: {catalog.source.osm_timestamp}. Связных направленных пар: {catalog.coverage.reachable_directed_pairs}.</p><Select showSearch optionFilterProp="label" style={{width:'100%'}} value={station} onChange={setStation} options={catalog.stations.map(s=>({value:s.id,label:s.name}))}/><div style={{maxHeight:220,overflow:'auto'}}>{catalog.stations.find(s=>s.id===station)?.observed_ways.map(w=><p key={w.osm_way_id}><a href={`https://www.openstreetmap.org/way/${w.osm_way_id}`} target="_blank" rel="noreferrer">Линия OSM {w.osm_way_id}</a> · обозначение {w.reference_tag||'не задано'} · {w.service||'назначение не задано'} · {Math.round(w.geometry_length_within_500m_m)} м фрагментов в радиусе 500 м</p>)}</div><details><summary>Исключённые объекты: {catalog.coverage.skipped.length}</summary><p>В основном LRT, дубли точек или отсутствие привязки к графу обычной железной дороги.</p>{catalog.coverage.skipped.map((s,i)=><p key={i}>{s.name||'Без названия'}: {s.reason}</p>)}</details></>}</details>;
}
