import {useEffect,useState} from 'react';
import {App,Button,InputNumber,Select} from 'antd';
import {api} from './store';
import type {Snapshot,Topology} from './types';
type Report={context:{sim_time_s:number};rotation:{feasible:boolean;reason?:string;fleet_required:number;crews_required:number;note:string;assignments:{train_id:string;unit_id:string;crew_reliefs:{station_id:string;crew_id:string}[]}[]};wear:{note:string;tracks:{resource:string;estimated_pct:number;equivalent_million_tonnes:number}[]};recovery:{restrictions:{block_id:string;action:string;trains_on_resource:string[]}[]}};
export function OperationsPanel({snapshot,topology,disabled}:{snapshot:Snapshot;topology:Topology;disabled:boolean}){
 const {message}=App.useApp();const [data,setData]=useState<Report|null>(null),[error,setError]=useState('');
 const [origin,setOrigin]=useState(topology.stations[0].id),[destination,setDestination]=useState(topology.stations.at(-1)!.id),[count,setCount]=useState(20),[orders,setOrders]=useState<{origin:string;destination:string;count:number}[]>([]),[allocation,setAllocation]=useState('');
 const [train,setTrain]=useState(snapshot.trains[0].id),[power,setPower]=useState(4),[regen,setRegen]=useState(0),[receptivity,setReceptivity]=useState(0);
 const refresh=()=>api<Report>('/logic/operations').then(v=>{setData(v);setError('');}).catch(e=>setError(e.message));
 useEffect(()=>{let alive=true;setData(null);api<Report>('/logic/operations').then(v=>{if(alive)setData(v);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[snapshot.epoch,snapshot.active_plan_id,snapshot.awaiting_plan]);
 const [section,setSection]=useState(topology.sections[0].id),[grade,setGrade]=useState(0),[radius,setRadius]=useState<number|null>(null),[cant,setCant]=useState(0);
 const name=(id:string)=>topology.stations.find(s=>s.id===id)?.name||id;
 const options=topology.stations.map(s=>({value:s.id,label:s.name}));
 return <section className="panel fleet-editor"><h3>Парк, износ и восстановление</h3><label>Бюджет расчёта<Select disabled={disabled} value={snapshot.planning_budget_s||5} options={[2,5,10,15,20,30].map(value=>({value,label:`${value} секунд`}))} onChange={async seconds=>{try{await api("/dispatch/planning-budget","POST",{epoch:snapshot.epoch,seconds});}catch(e){message.error((e as Error).message);}}}/></label><p>Мягкий лимит: профили и передача результата требуют дополнительного времени. Для общей сети используется один сбалансированный вариант.</p><Button onClick={refresh}>Обновить расчёт</Button>{error&&<p role="alert">{error}</p>}{data&&<><p>Состояние на {Math.round(data.context.sim_time_s/60)} мин модели</p><details><summary>Оборот: {data.rotation.fleet_required??'—'} составов · {data.rotation.crews_required??'—'} бригад</summary><p>{data.rotation.note||data.rotation.reason}</p>{data.rotation.assignments?.map(a=><p key={a.train_id}>{a.train_id} → {a.unit_id}; {a.crew_reliefs.map(c=>`${c.crew_id}: ${name(c.station_id)}`).join(', ')}</p>)}</details><details><summary>Расчётный износ от выполненных проходов</summary><p>{data.wear.note}</p>{data.wear.tracks.map(t=><p key={t.resource}>{t.resource}: {t.estimated_pct.toFixed(6)}% · {t.equivalent_million_tonnes.toFixed(4)} млн экв. тонн</p>)}</details><details open={!!data.recovery.restrictions.length}><summary>Действия после сбоев</summary>{data.recovery.restrictions.length?data.recovery.restrictions.map(r=><p key={r.block_id}>{r.block_id}: {r.action} {r.trains_on_resource.join(', ')}</p>):<p>Активных ограничений нет.</p>}</details></>}
 <details><summary>Распределить порожние вагоны</summary><p>Добавьте заявки. Расчёт минимизирует порожний пробег; рейсы затем назначаются отдельно.</p><Select showSearch optionFilterProp="label" value={origin} onChange={setOrigin} options={options}/><Select showSearch optionFilterProp="label" value={destination} onChange={setDestination} options={options}/><InputNumber min={1} max={5000} precision={0} value={count} onChange={v=>setCount(v||1)}/><Button onClick={()=>{setOrders(x=>[...x,{origin,destination,count}]);setAllocation('');}}>Добавить заявку</Button>{orders.map((o,i)=><p key={i}>{name(o.origin)} → {name(o.destination)}: {o.count} <button onClick={()=>{setOrders(x=>x.filter((_,j)=>i!==j));setAllocation('');}}>×</button></p>)}<Button disabled={!orders.length} onClick={async()=>{const supplies:Record<string,number>={},demands:Record<string,number>={};orders.forEach(o=>{supplies[o.origin]=(supplies[o.origin]||0)+o.count;demands[o.destination]=(demands[o.destination]||0)+o.count;});try{const r=await api<{feasible:boolean;empty_wagon_km:number;flows:{origin:string;destination:string;wagons:number}[]}>('/logic/empty-wagons','POST',{supplies,demands});setAllocation(r.feasible?`${r.empty_wagon_km.toFixed(1)} вагоно-км. `+r.flows.map(f=>`${name(f.origin)} → ${name(f.destination)}: ${f.wagons}`).join('; '):'Нет связного решения');}catch(e){message.error((e as Error).message);}}}>Рассчитать</Button><p>{allocation}</p></details>
 <details><summary>Физика будущего рейса</summary><p>Модельные параметры. Рекуперация учитывает долю энергии, принимаемую сетью; значение 0 отключает её.</p><Select value={train} onChange={setTrain} options={snapshot.trains.map(t=>({value:t.id,label:t.number}))}/><label>Мощность на колёсах, МВт<InputNumber min={0.1} max={20} value={power} onChange={v=>setPower(v||1)}/></label><label>КПД рекуперации, %<InputNumber min={0} max={100} value={regen} onChange={v=>setRegen(v||0)}/></label><label>Приём энергии сетью, %<InputNumber min={0} max={100} value={receptivity} onChange={v=>setReceptivity(v||0)}/></label><Button disabled={disabled} onClick={async()=>{try{await api('/dispatch/physics','POST',{epoch:snapshot.epoch,train_id:train,traction_power_w:power*1e6,regenerative_efficiency:regen/100,grid_receptivity:receptivity/100,regenerative_power_w:power*1e6});message.success('Параметры сохранены; требуется новый проверенный план');}catch(e){message.error((e as Error).message);}}}>Применить к рейсу</Button></details><details><summary>Учебный профиль неиспользованного перегона</summary><p>Знак уклона задаётся от первой станции ко второй. Радиус применяется ко всему перегону как консервативное ограничение; допуск непогашенного возвышения в модели — 100 мм. Параметры не подтверждены обследованием.</p><Select showSearch optionFilterProp="label" value={section} onChange={setSection} options={topology.sections.map(s=>({value:s.id,label:`${name(s.from_station)} → ${name(s.to_station)}`}))}/><label>Уклон, ‰<InputNumber min={-40} max={40} value={grade} onChange={v=>setGrade(v||0)}/></label><label>Радиус кривой, м · пусто для прямой<InputNumber min={50} max={100000} value={radius} onChange={setRadius}/></label><label>Возвышение, мм<InputNumber min={0} max={200} value={cant} onChange={v=>setCant(v||0)}/></label><Button disabled={disabled} onClick={async()=>{try{await api('/dispatch/section-physics','POST',{epoch:snapshot.epoch,section_id:section,grade_permille:grade,curve_radius_m:radius,cant_mm:cant});message.success('Профиль изменён; требуется новый проверенный план');}catch(e){message.error((e as Error).message);}}}>Применить профиль</Button></details></section>;
}
