import type {Metrics,QualityComponent,Topology} from './types';
import {clock,minutes} from './store';
import {Tag} from 'antd';
import {qualityNames,qualityDriver,qualityStatus} from './quality';

const violationNames:Record<string,string>={occupancy:'Перегон',switch:'Стрелочная горловина',capacity:'Вместимость станции',closed:'Закрытие',signal:'Сигнал',delay:'Задержка',past:'Устаревшее отправление',physics:'Время движения',dwell:'Стоянка',clearance:'Освобождение пути',route:'Маршрут',horizon:'Горизонт расчёта'};

export function QualityDetails({metrics,topology}:{metrics:Metrics;topology?:Topology}) {
 const current=(metrics.quality_version||1)>=3;
 const capacity=metrics.capacity;
 const status=qualityStatus(metrics);
 const geometric=metrics.formula?.aggregation==='weighted_geometric';
 const thresholds=metrics.formula?.thresholds??{normal:90,attention:70};
 const arrivals=metrics.terminal_arrivals;
 const section=(id:string)=>{const s=topology?.sections.find(s=>s.id===id);const name=(id:string)=>topology?.stations.find(s=>s.id===id)?.name||id;return s?name(s.from_station)+' — '+name(s.to_station):id;};
 return <div className="quality-details">
  <div className="quality-total">{metrics.index.toFixed(1)} <small>/ 100 · {metrics.forecast?'прогноз':'текущий индекс'}</small> <Tag color={status.color}>{status.label}</Tag></div>
  <p className="subtle">Норма: ≥ {thresholds.normal}. Внимание: от {thresholds.attention} до {thresholds.normal}. Критично: ниже {thresholds.attention}.</p>
  {geometric&&<p className="subtle">Потери распределены пропорционально логарифмическому вкладу показателей. При нулевых оценках — между ними по весам.</p>}
  {current?<p>{qualityDriver(metrics)}. Оценки без данных нейтральны и отмечены ниже.</p>:<p>Архивная формула v{metrics.quality_version||1}. Её оценки не сравниваются с текущей формулой.</p>}
  {metrics.components&&<div className="dispatch-scroll"><table className="dispatch-table quality-scores"><thead><tr><th>Показатель</th><th>Оценка / 100</th><th>Вес</th><th>Потеря баллов</th></tr></thead><tbody>{Object.entries(metrics.components).map(([key,item])=>item&&<tr key={key}><td>{!current&&key==='schedule'?'Соблюдение графика':!current&&key==='arrival_accuracy'?'Прибытия на станции':qualityNames[key as QualityComponent]}{item.observed===false&&<small>Пока нет данных · нейтрально</small>}</td><td><b>{item.score.toFixed(1)}</b><progress aria-label={qualityNames[key as QualityComponent]} max={100} value={item.score}/></td><td>{(item.weight*100).toFixed(0)}%</td><td>{item.loss_points!==undefined?'−'+item.loss_points.toFixed(1):'—'}</td></tr>)}</tbody></table></div>}
  <dl className="quality-facts">
   <div><dt>Задержка по прибытиям на станции</dt><dd>{minutes(metrics.total_delay_s)}</dd></div>
   {metrics.departures&&<div><dt>Отклонение отправлений</dt><dd>{minutes(metrics.departures.deviation_s)} · {metrics.departures.evaluated} оценено</dd></div>}
   <div><dt>Перегоны без сбоев</dt><dd>{metrics.available_sections??'—'} / {metrics.total_sections??'—'}</dd></div>
   <div><dt>Нарушения текущего расписания</dt><dd>{metrics.conflicts}</dd></div>
   <div><dt>{current?'Точность конечного прибытия':'Точность прибытия'}</dt><dd>{current?(arrivals?.on_time_pct===null?'Пока нет данных':arrivals?.on_time_pct+'%'):(metrics.on_time_pct===null?'Пока нет данных':`${metrics.on_time_pct}%`)}</dd></div>
   {arrivals&&<div><dt>Конечные прибытия: вовремя / оценено</dt><dd>{arrivals.on_time} / {arrivals.evaluated} · ожидаются {arrivals.pending}</dd></div>}
   <div><dt>Энергия / исходный план на том же пути</dt><dd>{metrics.energy_kwh.toFixed(1)} / {metrics.reference_energy_kwh?.toFixed(1)??'—'} кВт·ч</dd></div>
   {metrics.energy&&<div><dt>{metrics.energy.saved_kwh>=0?'Экономия энергии':'Перерасход энергии'}</dt><dd>{Math.abs(metrics.energy.saved_kwh).toFixed(1)} кВт·ч{metrics.energy.saved_pct!==null?' · '+Math.abs(metrics.energy.saved_pct).toFixed(2)+'%':''}</dd></div>}
  </dl>
  {capacity&&<details className="quality-capacity" open><summary>Использование перегонов · {metrics.forecast?'горизонт исходного плана':'последние 15 минут'}</summary><p>{clock(capacity.window_start_s)} — {clock(capacity.window_end_s)}. Занято {capacity.utilization_pct===null?'—':capacity.utilization_pct.toFixed(1)+'%'} времени путей. Пройдено {(capacity.distance_m/1000).toFixed(1)} из {(capacity.reference_distance_m/1000).toFixed(1)} поездо-км по исходному графику.</p><div className="dispatch-scroll"><table className="dispatch-table"><thead><tr><th>Перегон</th><th>Сбой сейчас</th><th>Занятость</th><th>Проезд / план, км</th></tr></thead><tbody>{capacity.sections.map(s=><tr key={s.section_id}><td>{section(s.section_id)}</td><td>{s.blocked_now?'Действует':'Нет'}</td><td>{s.utilization_pct===null?'—':s.utilization_pct.toFixed(1)+'%'}</td><td>{(s.distance_m/1000).toFixed(1)} / {(s.reference_distance_m/1000).toFixed(1)}</td></tr>)}</tbody></table></div><p>Высокая занятость сама по себе не повышает индекс. Сравнивается выполненный проезд с исходным графиком; доля перегонов без сбоев учитывается отдельно. Это модель использования участка, не нормативная пропускная способность.</p></details>}
  {metrics.conflict_summary&&<details className="quality-conflicts"><summary>Проверка расписания · {metrics.conflict_summary.total} нарушений</summary><p>Конфликты ресурсов: {metrics.conflict_summary.resource_conflicts}; ограничения сбоев: {metrics.conflict_summary.restriction_violations}; остальные проверки: {metrics.conflict_summary.other_violations}. Это нарушения плана, а не зарегистрированные столкновения.</p>{Object.entries(metrics.conflict_summary.by_code).map(([code,count])=><p key={code}>{violationNames[code]||code}: {count}</p>)}</details>}
  <details className="quality-formula"><summary>Формула и допущения</summary>{current?<><p>{geometric?'Индекс = 100 × произведение (оценка / 100) в степени доли показателя. Нулевая оценка с ненулевым весом обнуляет индекс.':'Индекс = сумма (доля × оценка).'} Отправления: 100 × max(0, 1 − сумма абсолютных отклонений / {metrics.formula?.delay_norm_s} с). Просроченные отправления учитываются до фактического выезда.</p><p>Использование участка: доля перегонов без закрытия или сбоя сигнала × min(100, выполненный проезд / исходный проезд × 100). До ожидаемого движения проезд нейтрален. Занятость — доля времени от въезда до освобождения хвостом, с объединением перекрывающихся интервалов.</p><p>Энергия: 100 × max(0, 1 − перерасход / {metrics.formula?.energy_norm_kwh} кВт·ч). Расход сравнивается на одинаковом пройденном пути. Экономия показывается отдельно: оценка ограничена 100.</p><p>Нарушения: 100 / (1 + {metrics.formula?.conflict_penalty??1} × число нарушений расписания). Конечное прибытие: доля поездов в пределах ±{metrics.formula?.arrival_tolerance_s} с исходного расписания. Просроченное незавершённое прибытие считается опозданием.</p><p>Демо-формула v{metrics.quality_version}: {geometric?'геометрическое среднее':'взвешенное среднее'}. Доли показателей приведены в таблице. Настройки сохранены вместе с оценкой. Текущие показатели и прогноз используют разные периоды и не являются оценкой выигрыша друг относительно друга.</p></>:<p>Архивная формула учитывала задержки на станциях, энергию, открытые перегоны и нарушения. Снимок сохранён без пересчёта.</p>}</details>
 </div>;
}
