export interface Station {id:string;name:string;position_m:number;coordinate:[number,number];tracks:number}
export interface Section {id:string;from_station:string;to_station:string;length_m:number;speed_limit_mps:number;geometry:[number,number][]}
export interface Topology {stations:Station[];sections:Section[];length_m:number;assumptions:string[]}
export interface Train {coordinate:[number,number];bearing_deg:number;origin_id:string;destination_id:string;route_station_ids:string[];route_name:string;position_source:string;id:string;number:string;type:'passenger'|'freight';direction:number;position_m:number;speed_mps:number;delay_s:number;energy_kwh:number;status:string;station_id:string|null;section_id:string|null;eta_s:number|null;mass_kg:number;length_m:number;max_speed_mps:number}
export interface Movement {train_id:string;leg:number;section_id:string;start_s:number;end_s:number;release_s:number}
export interface Metrics {index:number;total_delay_s:number;max_delay_s:number;weighted_delay_s:number;passenger_delay_s:number;energy_kwh:number;conflicts:number;completed_trips:number;scheduled_trips:number;on_time_pct:number|null}
export type QualityComponent='schedule'|'energy'|'capacity'|'conflicts'|'arrival_accuracy'|'availability'|'plan_validity';
export interface QualityScore {score:number;weight:number;loss_points?:number;observed?:boolean}
export type QualityMethod='weighted_mean'|'weighted_geometric';
export type QualityWeights=Record<'schedule'|'energy'|'capacity'|'conflicts'|'arrival_accuracy',number>;
export interface QualityFormula {version:number;weights:Record<string,number>;delay_norm_s:number;energy_norm_kwh:number;arrival_tolerance_s:number;capacity_window_s:number;aggregation?:QualityMethod;conflict_penalty?:number;thresholds?:{normal:number;attention:number}}
export interface ScenarioSettings {passenger_weight:number;freight_weight:number;delay_weight:number;energy_weight:number;delay_norm_s:number;energy_norm_kwh:number;arrival_tolerance_s:number;quality_weights:QualityWeights;quality_formula:QualityMethod;quality_threshold_normal:number;quality_threshold_attention:number;conflict_penalty:number}
export interface Punctuality {evaluated:number;on_time:number;late:number;early:number;deviation_s:number;delay_s:number;on_time_pct:number|null;pending?:number}
export interface CapacityMetrics {window_start_s:number;window_end_s:number;window_s:number;basis:'baseline_horizon'|'rolling_15_minutes';availability_pct:number;utilization_pct:number|null;entry_blocked_pct:number|null;distance_m:number;reference_distance_m:number;delivery_pct:number|null;score:number;sections:{section_id:string;blocked_now:boolean;occupied_s:number;entry_blocked_s:number;utilization_pct:number|null;distance_m:number;reference_distance_m:number}[]}
export interface Metrics {quality_version?:number;quality_signature?:string;forecast?:boolean;forecast_valid?:boolean|null;assessment?:'on_track'|'attention'|'disrupted';blocked_sections?:string[];available_sections?:number;total_sections?:number;reference_energy_kwh?:number;evaluated_arrivals?:number;components?:Partial<Record<QualityComponent,QualityScore>>;drivers?:{component:QualityComponent;loss_points:number}[];departures?:Punctuality;terminal_arrivals?:Punctuality;capacity?:CapacityMetrics;energy?:{used_kwh:number;reference_kwh:number;saved_kwh:number;saved_pct:number|null};conflict_summary?:{total:number;resource_conflicts:number;restriction_violations:number;other_violations:number;by_code:Record<string,number>};formula?:QualityFormula}
export interface QualityPoint {sim_time_s:number;state_version:number;index:number}
export interface QualityResponse {epoch:string;active_plan_id:string;constraint_version:number;state_version:number;sim_time_s:number;actual:Metrics;forecast:Metrics|null;trend:{quality_signature:string;window_start_s:number;window_end_s:number;points:QualityPoint[];sample_count:number}}
export interface Plan {id:string;label:string;status:string;movements:Movement[];metrics:Metrics;calculation_s:number;within_budget:boolean;reason:string;violations:{code:string;message:string;train_id?:string}[]}
export interface Snapshot {sim_time_s:number;state_version:number;epoch:string;running:boolean;speed:number;trains:Train[];sections:{id:string;status:string;occupying:string[];signal:string}[];switches:{station_id:string;available:boolean;position:string}[];metrics:Metrics;active_plan_id:string;plan:Plan;awaiting_plan:boolean;replanning:boolean;incidents:Incident[]}
export interface Profile {train_id:string;plan_id:string;epoch:string;constraint_version:number;points:number[][];energy_kwh:number|null;arrival_s:number|null;reachable:boolean;provisional:boolean}
export interface SpeedAdvice {plan_id:string;sim_time_s:number;current_speed_mps:number;recommended_speed_mps:number;lookahead_speed_mps:number;lookahead_s:number;limit_mps:number;phase:'waiting'|'held'|'accelerating'|'cruising'|'braking'|'completed';reason:string;section_id:string|null;next_station_id:string|null;departure_s:number|null;next_arrival_s:number|null;final_arrival_s:number|null;energy_remaining_kwh:number|null;energy_plan_kwh:number|null;energy_saving_kwh:number|null;energy_saving_pct:number|null;forecast_available:boolean;source:'simulation'}
export interface Train {speed_advice?:SpeedAdvice}
export interface Snapshot {constraint_version?:number}
export interface EcoSummary {train_id:string;saving_kwh:number;saving_pct:number;before_energy_kwh:number;after_energy_kwh:number;final_arrival_s:number;changes:{leg:number;section_id:string;before_arrival_s:number;after_arrival_s:number;extra_running_s:number;saving_kwh:number;before_cruise_mps:number;after_cruise_mps:number}[]}
export interface Plan {eco?:EcoSummary}
export interface EcoResult {plan:Plan|null;profile?:Profile;reason:'proposal_ready'|'no_safe_slack'|'awaiting_valid_plan';epoch:string;base_plan_id:string;constraint_version:number;sim_time_s:number}
export interface RealtimeMetadata {protocol_version:1;stream_id:string;seq:number;observed_at:string;source:'simulation';update_interval_ms:number}
export interface Snapshot {realtime?:RealtimeMetadata}
export interface DispatchConflict {code:string;kind:string;message:string;resource?:string;station_id?:string;section_id?:string;train_id?:string;other_train_id?:string;start_s?:number;end_s?:number}
export interface DispatchDecision extends Movement {station_id:string;priority:number;lateness_weight:number;ready_s:number;wait_s:number;remaining_wait_s:number;action:'passing'|'completed'|'held'|'wait'|'ready';committed:boolean;reason:string;predecessors:{train_id:string;resource:string;release_s:number}[]}
export interface DispatchSummary {valid:boolean;conflicts:DispatchConflict[];policy:string;next_decisions:DispatchDecision[]}
export interface DispatchReport extends DispatchSummary {plan_id:string;epoch:string;state_version:number;sim_time_s:number;active:boolean;applicable:boolean;decisions:DispatchDecision[];section_order:{section_id:string;reservations:Movement[]}[]}
export interface Snapshot {dispatch?:DispatchSummary}
export interface Incident {id:string;kind:string;target_id:string;start_s:number;end_s:number;status?:'active'|'resolved'|'expired';resolved_s?:number;scheduled_end_s?:number}
export interface ReplanningOptions {auto_apply:boolean;policy:'balanced'|'passenger_priority'}
export interface ReplanMovementChange {train_id:string;leg:number;section_id:string;before_s:number;after_s:number;change_s:number;before_arrival_s?:number;after_arrival_s?:number;before_release_s?:number;after_release_s?:number}
export interface ReplanComparison {committed_total?:number;old_plan_id:string;new_plan_id:string;committed_preserved:number;violations_before:number;before:Metrics;after:Metrics;changes:ReplanMovementChange[];trains:{train_id:string;before_arrival_s:number;after_arrival_s:number;change_s:number}[];version?:number;basis?:'forecast_at_evaluation'|'forecast_at_application';evaluated_at_s?:number;epoch?:string;constraint_version?:number;old_plan_label?:string;new_plan_label?:string;calculation_s?:number|null}
export interface PlanComparisonResponse {epoch:string;constraint_version:number;active_plan_id:string;plan_id:string;sim_time_s:number;applicable:boolean;comparison:ReplanComparison}
export interface ReplanStatus {status:'idle'|'queued'|'calculating'|'review'|'applied'|'failed';automatic?:boolean;job_id?:string;trigger?:string;policy?:string;attempt?:number;elapsed_s?:number;message?:string|null;recommended_plan_id?:string;applied_plan_id?:string;comparison:ReplanComparison|null}
export interface Snapshot {replanning_options?:ReplanningOptions;replan_status?:ReplanStatus}
export interface Snapshot {clock_held_for_replan?:boolean}
