// Uses the supplied Codex presentation runtime; editable PPTX + browser slide companion.
// Set RUNTIME_NODE_MODULES, RUNTIME_PYTHON and RAIL_PRESENTATION_SKILL to the supplied runtime.
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'..');
const modules=process.env.RUNTIME_NODE_MODULES;
const skill=process.env.RAIL_PRESENTATION_SKILL;
if(!modules||!skill||!process.env.RUNTIME_PYTHON)throw Error('Set the documented presentation runtime variables.');
const require=createRequire(path.join(modules,'package.json'));
const {Presentation,PresentationFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')));
const {finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')));
const backend=JSON.parse(await fs.readFile(path.join(root,'artifacts/backend-results.json'),'utf8'));
const browser=JSON.parse(await fs.readFile(path.join(root,'artifacts/browser-results.json'),'utf8'));
const tests=JSON.parse(await fs.readFile(path.join(root,'artifacts/test-results.json'),'utf8'));
const out=path.join(root,'artifacts');const tmp=path.join(root,'.build/deck');
await fs.mkdir(tmp,{recursive:true});await fs.mkdir(out,{recursive:true});
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={bg:'#F7F9F3',ink:'#213B32',green:'#247953',muted:'#637869',cream:'#DCE8C4'};
const font='DejaVu Sans';const html=[];
function text(s,content,x,y,w,h,size=26,color=C.ink,bold=false){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=content;a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return a;}
function slide(title,notes=''){const s=p.slides.add();s.background.fill=C.bg;text(s,title,72,53,1136,80,44,C.ink,true);text(s,'RAILFLOW / DEMONSTRATION',72,666,900,25,14,C.muted);text(s,String(p.slides.items.length).padStart(2,'0'),1155,663,60,26,17,C.muted);s.speakerNotes.textFrame.setText(notes+'\nSources: project code, preserved network.json, docs/RULES.md and artifacts/*-results.json. This is not certified railway safety equipment.');return s;}
function body(s,lines,y=190,step=98){lines.forEach((line,i)=>text(s,line,76,y+i*step,1090,step-12,27));}
function htmlSlide(title,paragraphs){html.push({title,paragraphs});}
function box(s,label,x,y,w,h){const b=s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill:'#E7EEDF',line:{fill:'#9AAF94',width:1}});b.text=label;b.text.style={typeface:font,fontSize:24,bold:true,color:C.ink,alignment:'center',verticalAlignment:'middle'};return b;}
function arrow(s,x,y,w=80,h=24,direction='right'){s.shapes.add({geometry:`${direction}Arrow`,position:{left:x,top:y,width:w,height:h},fill:'#7F9D79',line:{fill:'none',width:0}});}

{
const s=p.slides.add();s.background.fill=C.green;text(s,'Railflow',72,182,1136,125,94,'#FFFFFF',true);text(s,'Railway dispatch prototype',77,325,1090,74,43,C.cream);text(s,'ALT University · Hackathon',78,437,1090,45,27,'#FFFFFF');text(s,'Demonstration and advisory system.\nNot a replacement for certified railway safety systems.',78,574,1080,70,23,C.cream);s.speakerNotes.textFrame.setText('Working full-stack prototype built on the supplied immutable railway map. All infrastructure and performance claims are scoped to the demonstration.');htmlSlide('Railflow',['Railway dispatch prototype','ALT University · Hackathon','Demonstration and advisory system. Not a replacement for certified railway safety systems.']);
}
{
const s=slide('Dispatch decisions under disruption');body(s,['Opposing and following services share finite track capacity.','Priority changes and incidents require a new feasible plan.','Dispatchers need to see who moves, who waits, and why.','The prototype explains each decision and records its outcome.'],180,99);htmlSlide('Dispatch decisions under disruption',['Opposing and following services share finite track capacity.','Priority changes and incidents require a feasible plan.','Every movement needs an authority, an explanation and a traceable outcome.']);
}
{
const s=slide('The railway stays unchanged','Four original assets are protected by SHA-256 regression checks. Source metadata does not contain verified switch tables, platform capacities or physical signal placements.');text(s,'49,682',75,185,460,110,76,C.green,true);text(s,'original track edges',80,295,450,55,28);text(s,'841',685,185,450,110,76,C.green,true);text(s,'synthetic source ways excluded',690,295,490,75,28);text(s,'Only existing adjacency is routable.\nA visual crossing never creates a new connection.',78,415,1100,105,30);text(s,'Map geometry, labels and styles remain in the original files.\nTrains, signals, occupancy and incidents are separate overlays.',78,553,1090,75,24,C.muted);htmlSlide('The railway stays unchanged',['49,682 original edges; 841 synthetic ways excluded from dispatching.','Original geometry, labels and styles are preserved byte-for-byte.','Only existing adjacency is routable. Unknown platforms and switch tables are disclosed.']);
}
{
const s=slide('One authoritative simulation','Architecture diagram is editable. All mutation and physics run in one process. SSE sends versioned snapshots to the dashboard and map overlays.');box(s,'Dashboard\nREST commands',76,210,220,115);arrow(s,314,253,43);box(s,'Validation\nREST API',375,210,220,115);arrow(s,613,253,43);box(s,'Simulation\n0.2 s steps',674,210,230,115);arrow(s,924,253,43);box(s,'SQLite history\nBounded\nevent bus',987,210,220,115);box(s,'Original graph\nRead-only router',375,425,220,115);arrow(s,613,465,43);box(s,'Dispatch + ATO\nQuality factors',674,425,230,115);arrow(s,775,346,28,57,'up');text(s,'Versioned SSE snapshots update the dashboard every 0.5 s',76,584,1120,60,29,C.green,true);htmlSlide('One authoritative simulation',['The dashboard sends commands through a validated REST API to the fixed-step simulation.','The original graph supplies dispatch, advisory ATO and quality services.','SQLite stores the journal and replay. A bounded event bus publishes SSE twice per second.']);
}
{
const s=slide('A transparent dispatch preference','I=(importance-1)/9; D=min(predicted_positive_delay_seconds/300,1); W=eligible_wait_seconds/300, uncapped; E=min(remaining_traction_kWh/1000,1). Importance is independent of train category. FIFO tier after 300 s. Ties: departure time, then train ID.');text(s,'P = 4I + 2D + 3W − E',78,180,1100,100,59,C.green,true);text(s,'I = (importance − 1) / 9, input 1–10',78,310,535,55,25);text(s,'D = min(delay / 300 s, 1)',660,310,540,55,25);text(s,'W = eligible wait / 300 s',78,384,535,55,25);text(s,'E = min(remaining kWh / 1000, 1)',660,384,545,75,25);text(s,'After 300 s, feasible waiting trains enter a protected FIFO tier.',78,492,1100,65,27);text(s,'Occupancy, route compatibility and committed authority are mandatory.',78,593,1100,65,26,C.ink,true);htmlSlide('A transparent dispatch preference',['P = 4I + 2D + 3W − E','I = (importance−1)/9. D = min(positive delay/300 s,1). W = eligible wait/300 s. E = min(remaining traction kWh/1000,1).','Importance ranges from 1 to 10. Waiting has no cap.','Protected FIFO after 300 seconds. Departure time and train ID break ties. Mandatory constraints always apply.']);
}
{
const s=slide('Authority, occupancy and signals');text(s,'Rear clearance = head − length − 25 m',77,185,1130,85,42,C.green,true);body(s,['Reserve an entire movement to its next stop, atomically.','Release a block only after the complete train clears it.','Keep junction locks and committed routes when importance changes.','Red holds entry. Green grants authority. Yellow governs approach.'],308,77);htmlSlide('Authority, occupancy and signals',['Original edges and junction vertices form exclusive resources. Station capacity is conservatively one mapped vertex.','Rear clearance = head − train length − 25 m.','Signals and train behavior use the same authority, incident and switch state.']);
}
{
const s=slide('Passing on an existing loop','Siding E47083 is 997.44 m. Usable length is 947.44 m at 25 m end clearances. Approaches E47073/E47069. Bypass E47072/E47071/E47070. Demo boundary vertices V39875/V39870 are track points, not renamed stations. Image: local application browser screenshot, artifacts/map-demo.png.');text(s,'997.44 m',77,182,540,100,66,C.green,true);text(s,'existing siding E47083\n947.44 m usable after clearances',81,288,540,88,27);text(s,'The local waits clear of both junctions.\nThe express uses the original bypass.',79,424,535,130,28);text(s,'A 980 m train does not fit and is rejected.',79,582,1100,55,27,C.ink,true);s.images.add({blob:await fs.readFile(path.join(out,'map-demo.png')),contentType:'image/png',alt:'Application map showing the original railway and separate train overlays',fit:'contain',position:{left:650,top:182,width:555,height:360}});htmlSlide('Passing on an existing loop',['Siding E47083 is 997.44 m long, with 947.44 m usable after clearances.','The local waits clear of both junctions. The express uses the existing bypass.','The overtaking scenario finishes both trains. A 980 m consist is rejected.']);
}
{
const s=slide('Incidents and recovery','Incident kinds: train delay/breakdown, failed signal, track closure and temporary speed restriction. Batch validation is atomic. Unknown clearance gives unknown ETA. Late incidents require physical braking inside existing authority.');body(s,['Create a delay, breakdown, signal failure, closure or restriction.','Identify affected trains and reconsider the plan immediately.','Compare existing detours with waiting for clearance.','Already inside? Brake and hold the occupied route until recovery.'],180,99);htmlSlide('Incidents and recovery',['Five incident types, targeted assets, durations or manual clearance.','Seeded random incidents and atomic batches of ten.','Compare detour and hold forecasts; keep locks during braking and recover consistently.']);
}
{
const s=slide('Driving advice and traction energy','v and target speed vₜ are m/s, braking b is m/s² and distance d is m. F = 0.0015 × mass_kg × 9.81 + 0.8 × mean_speed_mps². ΔKE = 0.5 × mass_kg × (v_new² − v_old²), in joules.');text(s,'v ≤ √(vₜ² + 2bd)',78,174,1100,95,62,C.green,true);text(s,'Target speed vₜ, braking b, distance d. SI units throughout.',78,282,1100,55,25,C.muted);text(s,'The advice respects signals, authority and scheduled stops.\nTimetable slack can reduce the recommended cruise speed.',78,359,1100,90,28);text(s,'ΔE (kWh) = [FΔx + max(0, ΔKE)] / (0.85 × 3,600,000)',78,478,1100,65,31,C.ink,true);text(s,'Rolling coefficient 0.0015, aerodynamic coefficient 0.8\n85% efficiency. No gradients or regenerative braking.',78,560,1100,75,25,C.muted);htmlSlide('Driving advice and traction energy',['Braking envelope: v ≤ √(vₜ² + 2bd), using SI units.','The dashboard compares recommended and actual speed and shows an arrival forecast.','ΔE (kWh) = [FΔx + max(0, ΔKE)] / (0.85 × 3,600,000).','The model includes rolling and aerodynamic resistance. It omits gradients and regenerative braking.']);
}
{
const s=slide('Movement quality, explained','Window: 300 simulation seconds by default. Schedule averages positive ETA/actual delay across eligible services and samples. Capacity uses moving/eligible train samples. Energy compares reference/actual increments. Conflict samples include invariant violations or an unresolved wait-for cycle. Stopping uses the maximum spatial error in the window. Neutral factors with no applicable observation are disclosed. Arrival time belongs only to S.');text(s,'Q = 30S + 20C + 20E + 20F + 10A',78,170,1110,95,45,C.green,true);body(s,['S  Schedule: max(0, 1 − mean positive delay / 300 s)','C  Capacity proxy: moving / eligible train samples','E  Energy: min(1, reference / actual traction energy)','F  Conflict freedom: 1 − fraction of conflict samples','A  Stop position: max(0, 1 − maximum error / 5 m)'],287,54);text(s,'Factors range from 0 to 1 over a rolling 300 s window.\nNo applicable observations: neutral factor 1. No observations: no score.',78,582,1110,76,23,C.muted);htmlSlide('Movement quality, explained',['Q = 30S + 20C + 20E + 20F + 10A, each factor in [0,1].','S = max(0,1−mean positive delay/300 s). C = moving/eligible train samples.','E = min(1,reference/actual energy). F = 1−fraction of conflict samples.','A = max(0,1−maximum stop error/5 m). Arrival time belongs only to S.','Rolling 300-second window. No applicable observation gives a neutral factor of 1. No observations means no score.']);
}
{
const s=slide('Measured prototype results',JSON.stringify({backend:backend.ten_incident_batch_ms,browser},null,2));
const replayChecks=browser.reconnect_verified&&browser.replay_read_only_verified&&browser.report_download_verified;
const scenarios=Object.values(backend.scenarios);
const constraintErrors=scenarios.reduce((sum,s)=>sum+s.constraint_errors,0);
const rows=[['Check','Observed','Target / scope'],['UI receipt to render, p95',`${browser.ui_receipt_to_render_ms.p95} ms`,'<500 ms'],['10 incidents, live SQLite',`${Math.round(browser.server_metrics.max_incident_batch_ms)} ms`,'<5,000 ms'],['10 incidents, in-memory max',`${backend.ten_incident_batch_ms.max} ms`,`${backend.ten_incident_batch_ms.trials} local trials`],['Automated checks',`${tests.passed} passed`,'Supplied graph'],['Reconnect / replay / CSV',replayChecks?'Verified':'Incomplete','Firefox browser']];
const table=s.tables.add({rows:rows.length,columns:3,left:76,top:184,width:1128,height:360,columnWidths:[540,250,338],values:rows});
table.borders.assign({fill:'#DCE5D4',width:1,style:'solid'});
for(let r=0;r<rows.length;r++){table.rows[r].height=60;for(let c=0;c<3;c++){const cell=table.getCell(r,c);cell.fill=r===0?C.green:r%2?'#FFFFFF':'#EDF2E7';cell.text.style={typeface:font,fontSize:23,bold:r===0,color:r===0?'#FFFFFF':C.ink};}}
text(s,`${constraintErrors} resource violations in ${scenarios.length} benchmark scenarios.\nLocal two-train tests. These are not production or certified safety results.`,78,580,1110,74,24,C.muted);
htmlSlide('Measured prototype results',rows.slice(1).map(r=>`${r[0]}: ${r[1]} (${r[2]})`).concat([`${constraintErrors} resource violations in ${scenarios.length} local two-train benchmark scenarios.`]));
}
{
const s=slide('Demonstration and limits');text(s,'Demo sequence',76,183,500,55,35,C.green,true);text(s,'1. Load passing and start at 120×\n2. Inspect siding hold and authority\n3. Create and clear an incident\n4. Replay and export the journal',78,263,535,255,27);text(s,'Current limitations',687,183,520,55,35,C.green,true);text(s,'Missing platform and switch metadata\nOne exclusive block per original edge\nHeuristic planning, approximate ETAs\nRestart does not restore live motion',690,263,520,255,26);text(s,'Advisory simulation only.\nNot a replacement for certified railway safety systems.',78,577,1120,80,26,C.ink,true);htmlSlide('Demonstration and limits',['Load passing and start at 120×. Inspect locks, create and clear an incident, then replay and export.','The source lacks platform and switch metadata. Every original edge is one exclusive block.','Planning and ETA forecasts use heuristics. Restart does not restore live motion.','Demonstration and advisory system. Not a replacement for certified railway safety systems.']);
}
const candidate=path.join(tmp,'candidate.pptx');
await (await PresentationFile.exportPptx(p)).save(candidate);
const finalPath=path.join(out,process.env.RAIL_DECK_NAME||'Railflow-Hackathon.pptx');
const result=await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath,pythonExecutable:process.env.RUNTIME_PYTHON,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit','--require-native-table-slide','11'],explicitTotalSlideCount:12,requiredNativeTableOwnerSlides:[11],requiredNativeChartOwnerSlides:[],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,`${path.basename(finalPath)}.validation.json`)});
for(let i=0;i<p.slides.items.length;i++){const image=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(tmp,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await image.arrayBuffer()));}
const escape=x=>x.replaceAll('&','&amp;').replaceAll('<','&lt;');
const webpage=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Railflow · Hackathon presentation</title><style>*{box-sizing:border-box}body{margin:0;background:#F7F9F3;color:#213B32;font:24px/1.55 Arial,sans-serif}section{display:none;min-height:100vh;padding:8vh 8vw 110px}section.active{display:flex;flex-direction:column;justify-content:center}h1{font-size:clamp(32px,4vw,65px);line-height:1.2;color:#247953;max-width:1100px}p{max-width:1100px;margin:13px 0}nav{position:fixed;bottom:25px;left:8vw;right:8vw;display:flex;align-items:center;gap:20px;font-size:15px}button{background:#247953;color:white;border:0;border-radius:5px;padding:10px 18px;cursor:pointer}nav span{margin-left:auto}small{font-size:14px;color:#637869}@media print{section,section.active{display:flex;page-break-after:always;min-height:100vh}nav{display:none}}</style>${html.map((s,i)=>`<section class="${i===0?'active':''}"><small>RAILFLOW · ${i+1} / 12</small><h1>${escape(s.title)}</h1>${s.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}</section>`).join('')}<nav><button onclick="go(-1)">← Previous</button><button onclick="go(1)">Next →</button><span id="count">1 / 12</span></nav><script>let index=0;function go(d){const slides=document.querySelectorAll('section');slides[index].classList.remove('active');index=(index+d+slides.length)%slides.length;slides[index].classList.add('active');document.querySelector('#count').textContent=(index+1)+' / 12';}document.onkeydown=e=>{if(e.key==='ArrowRight'||e.key===' ')go(1);if(e.key==='ArrowLeft')go(-1);};</script></html>`;
await fs.writeFile(path.join(out,'presentation.html'),webpage);
console.log(JSON.stringify({deck:result.finalPath,slides:p.slides.items.length,previews:tmp}));
